Repository ava-labs/hypersdk, pull requests merged in 2023-07, with the labels that each got.

#238 AvalancheGo@v1.10.4
  examples/tokenvm/go.mod
  examples/tokenvm/go.sum
  examples/tokenvm/scripts/run.sh
  go.mod
  go.sum
  vm/syncervm_client.go
Labels: dependencies

#241 Trigger CI with label
  .github/workflows/hypersdk-static-analysis.yml
  .github/workflows/hypersdk-unit-tests.yml
  .github/workflows/tokenvm-load-tests.yml
  .github/workflows/tokenvm-release.yml
  .github/workflows/tokenvm-static-analysis.yml
  .github/workflows/tokenvm-sync-tests.yml
  .github/workflows/tokenvm-unit-tests.yml
Labels: run CI, run release, run load

#248 Millisecond Block Time + Reduce Future Bound + Remove Block Cost
  builder/builder.go
  builder/dependencies.go
  builder/manual.go
  builder/time.go
  chain/base.go
  chain/block.go
  chain/builder.go
  chain/consts.go
  chain/dependencies.go
  chain/errors.go
  chain/execution_context.go
  chain/mock_action.go
  chain/mock_auth.go
  chain/mock_auth_factory.go
  chain/mock_rules.go
  chain/processor.go
  chain/transaction.go
  consts/consts.go
  examples/tokenvm/cmd/token-cli/cmd/action.go
  examples/tokenvm/cmd/token-cli/cmd/chain.go
  examples/tokenvm/cmd/token-cli/cmd/genesis.go
  examples/tokenvm/cmd/token-cli/cmd/prometheus.go
  examples/tokenvm/cmd/token-cli/cmd/root.go
  examples/tokenvm/cmd/token-cli/cmd/spam.go
  examples/tokenvm/config/config.go
  examples/tokenvm/controller/controller.go
  examples/tokenvm/genesis/genesis.go
  examples/tokenvm/genesis/rules.go
  examples/tokenvm/scripts/fix.lint.sh
  examples/tokenvm/scripts/run.sh
  examples/tokenvm/tests/e2e/e2e_test.go
  examples/tokenvm/tests/integration/integration_test.go
  examples/tokenvm/tests/load/load_test.go
  gossiper/consts.go
  gossiper/gossiper.go
  gossiper/manual.go
  gossiper/proposer.go
  rpc/dependencies.go
  rpc/jsonrpc_client.go
  rpc/jsonrpc_server.go
  scripts/fix.lint.sh
  utils/utils.go
  vm/dependencies.go
  vm/fees.go
  vm/mock_controller.go
  vm/resolutions.go
  vm/storage.go
  vm/vm.go
  vm/vm_test.go
Labels: run CI, run load

#257 Update to AvalancheGo@v1.10.5
  README.md
  chain/block.go
  chain/builder.go
  chain/dependencies.go
  chain/execution_context.go
  chain/mock_rules.go
  chain/processor.go
  chain/transaction.go
  examples/tokenvm/actions/export_asset.go
  examples/tokenvm/actions/import_asset.go
  examples/tokenvm/actions/outputs.go
  examples/tokenvm/actions/warp_transfer.go
  examples/tokenvm/cmd/token-cli/cmd/action.go
  examples/tokenvm/cmd/token-cli/cmd/chain.go
  examples/tokenvm/cmd/token-cli/cmd/key.go
  examples/tokenvm/cmd/token-cli/cmd/spam.go
  examples/tokenvm/cmd/token-cli/cmd/utils.go
  examples/tokenvm/controller/controller.go
  examples/tokenvm/genesis/errors.go
  examples/tokenvm/genesis/genesis.go
  examples/tokenvm/genesis/rules.go
  examples/tokenvm/go.mod
  examples/tokenvm/go.sum
  examples/tokenvm/rpc/jsonrpc_client.go
  examples/tokenvm/scripts/run.sh
  examples/tokenvm/tests/e2e/e2e_test.go
  examples/tokenvm/tests/integration/integration_test.go
  examples/tokenvm/tests/load/load_test.go
  go.mod
  go.sum
  gossiper/dependencies.go
  gossiper/proposer.go
  rpc/jsonrpc_client.go
  vm/dependencies.go
  vm/resolutions.go
  vm/vm.go
Labels: run CI, run load

#268 [x/sync] Fix Sync Panic
  examples/simplevm/go.mod
  examples/simplevm/go.sum
  examples/tokenvm/go.mod
  examples/tokenvm/go.sum
  go.mod
  go.sum
Labels: run sync

#276 Batch WebSocket Messages + Handle Ungraceful WebSocket Close
  cli/chain.go
  cli/spam.go
  codec/utils.go
  config/config.go
  examples/morpheusvm/config/config.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/tokenvm/config/config.go
  examples/tokenvm/tests/integration/integration_test.go
  pubsub/connection.go
  pubsub/connections.go
  pubsub/consts.go
  pubsub/errors.go
  pubsub/message_buffer.go
  pubsub/server.go
  pubsub/server_test.go
  rpc/consts.go
  rpc/dependencies.go
  rpc/errors.go
  rpc/websocket_client.go
  rpc/websocket_server.go
  vm/dependencies.go
  vm/resolutions.go
  vm/vm.go
Labels: run unit, run sync

#277 Add metrics to Pebble
  cli/cli.go
  examples/morpheusvm/controller/controller.go
  examples/morpheusvm/tests/load/load_test.go
  examples/tokenvm/controller/controller.go
  examples/tokenvm/tests/load/load_test.go
  pebble/metrics.go
  pebble/pebble.go
  storage/consts.go
  storage/storage.go
Labels: run unit, run sync

#280 Pre-allocate Memory in `codec.Packer`
  chain/base.go
  chain/block.go
  chain/dependencies.go
  chain/mock_action.go
  chain/mock_auth.go
  chain/result.go
  chain/transaction.go
  codec/optional_packer.go
  codec/optional_packer_test.go
  codec/packer.go
  codec/packer_test.go
  codec/utils.go
  consts/consts.go
  examples/morpheusvm/actions/transfer.go
  examples/morpheusvm/auth/ed25519.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/tokenvm/actions/burn_asset.go
  examples/tokenvm/actions/close_order.go
  examples/tokenvm/actions/create_asset.go
  examples/tokenvm/actions/create_order.go
  examples/tokenvm/actions/export_asset.go
  examples/tokenvm/actions/fill_order.go
  examples/tokenvm/actions/import_asset.go
  examples/tokenvm/actions/mint_asset.go
  examples/tokenvm/actions/modify_asset.go
  examples/tokenvm/actions/transfer.go
  examples/tokenvm/actions/warp_transfer.go
  examples/tokenvm/auth/ed25519.go
  examples/tokenvm/tests/integration/integration_test.go
  gossiper/proposer.go
  pubsub/message_buffer.go
  pubsub/server_test.go
  rpc/websocket_packer.go
  vm/warp_manager.go
Labels: run load, run unit, run sync

#288 Use FIFO Cache for Accepted Blocks
  cache/fifo.go
  config/config.go
  vm/dependencies.go
  vm/vm.go
  vm/vm_test.go
Labels: run load, run unit, run sync

#278 Update to AvalancheGo dev
  examples/morpheusvm/go.mod
  examples/morpheusvm/go.sum
  examples/tokenvm/go.mod
  examples/tokenvm/go.sum
  go.mod
  go.sum
Labels: run unit, run sync

#296 [e2e] Reduce state sync delay
  examples/morpheusvm/scripts/run.sh
  examples/tokenvm/scripts/run.sh
Labels: run sync

#298 [examples] Make persist tx optional
  examples/morpheusvm/config/config.go
  examples/morpheusvm/controller/controller.go
  examples/tokenvm/config/config.go
  examples/tokenvm/controller/controller.go
Labels: run unit, run sync

#297 create TypeID for Actions/Auths + delete reflection in Registry
  chain/block.go
  chain/dependencies.go
  chain/transaction.go
  codec/type_parser.go
  codec/type_parser_test.go
  examples/morpheusvm/actions/common.go
  examples/morpheusvm/actions/transfer.go
  examples/morpheusvm/auth/common.go
  examples/morpheusvm/auth/ed25519.go
  examples/morpheusvm/registry/registry.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/tokenvm/actions/burn_asset.go
  examples/tokenvm/actions/close_order.go
  examples/tokenvm/actions/common.go
  examples/tokenvm/actions/create_asset.go
  examples/tokenvm/actions/create_order.go
  examples/tokenvm/actions/export_asset.go
  examples/tokenvm/actions/fill_order.go
  examples/tokenvm/actions/import_asset.go
  examples/tokenvm/actions/mint_asset.go
  examples/tokenvm/actions/modify_asset.go
  examples/tokenvm/actions/transfer.go
  examples/tokenvm/auth/common.go
  examples/tokenvm/auth/ed25519.go
  examples/tokenvm/registry/registry.go
  examples/tokenvm/tests/integration/integration_test.go
  gossiper/manual.go
  gossiper/proposer.go
Labels: run load, run unit, run sync

#301 Final release nits
  cli/chain.go
  cli/prometheus.go
  cli/prompt.go
  cli/spam.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/prometheus.go
  examples/morpheusvm/demo.pk
  examples/morpheusvm/scripts/run.sh
  examples/morpheusvm/tests/e2e/e2e_test.go
  examples/tokenvm/DEVNETS.md
  examples/tokenvm/cmd/token-cli/cmd/prometheus.go
  examples/tokenvm/scripts/run.sh
  examples/tokenvm/tests/e2e/e2e_test.go
Labels: run load, run unit, run sync
