Repository ava-labs/hypersdk, pull requests merged in 2024-05, with the labels that each got.

#924 [vryx] Remove Fee Refund
  chain/builder.go
  chain/dependencies.go
  chain/mock_action.go
  chain/processor.go
  chain/result.go
  chain/transaction.go
  cli/chain.go
  cli/spam.go
  examples/morpheusvm/actions/transfer.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/resolutions.go
  examples/morpheusvm/controller/controller.go
  examples/morpheusvm/storage/state_manager.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/morpheusvm/tests/load/load_test.go
  examples/tokenvm/actions/burn_asset.go
  examples/tokenvm/actions/close_order.go
  examples/tokenvm/actions/consts.go
  examples/tokenvm/actions/create_asset.go
  examples/tokenvm/actions/create_order.go
  examples/tokenvm/actions/fill_order.go
  examples/tokenvm/actions/mint_asset.go
  examples/tokenvm/actions/transfer.go
  examples/tokenvm/cmd/token-cli/cmd/resolutions.go
  examples/tokenvm/cmd/token-wallet/backend/backend.go
  examples/tokenvm/controller/controller.go
  examples/tokenvm/controller/state_manager.go
  examples/tokenvm/tests/integration/integration_test.go
  examples/tokenvm/tests/load/load_test.go
  fees/manager.go
  fetcher/fetcher.go
  fetcher/fetcher_test.go
  rpc/jsonrpc_client.go
  tstate/tstate_test.go
  tstate/tstate_view.go
  x/programs/cmd/simulator/vm/storage/state_manager.go
Labels: vryx

#940 [tokenvm] Fix Demo
  examples/tokenvm/README.md
  examples/tokenvm/cmd/token-cli/cmd/action.go
  examples/tokenvm/cmd/token-cli/cmd/resolutions.go
  examples/tokenvm/cmd/token-cli/cmd/spam.go
  examples/tokenvm/cmd/token-wallet/app.go
Labels: bug

#946 [GH-905] Don't need _guest suffix
  x/programs/runtime/runtime.go
  x/programs/rust/sdk-macros/src/lib.rs
  x/programs/rust/wasmlanche-sdk/tests/public_function.rs
Labels: wasmlanche

#984 [testing] Migrate from gomega to testify
  examples/morpheusvm/go.mod
  examples/morpheusvm/scripts/run.sh
  examples/morpheusvm/scripts/tests.integration.sh
  examples/morpheusvm/tests/e2e/e2e_test.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/tokenvm/go.mod
  examples/tokenvm/scripts/run.sh
  examples/tokenvm/scripts/tests.integration.sh
  examples/tokenvm/tests/e2e/e2e_test.go
  examples/tokenvm/tests/integration/integration_test.go
Labels: testing

#986 [x/programs] Use memdb instead of pebble for simulator
  x/programs/cmd/simulator/vm/controller/controller.go
Labels: wasmlanche

#967 [x/programs] Improve simulator logs
  x/programs/cmd/simulator/cmd/plan.go
  x/programs/cmd/simulator/cmd/plan_test.go
  x/programs/cmd/simulator/cmd/program.go
  x/programs/cmd/simulator/cmd/root.go
  x/programs/cmd/simulator/src/lib.rs
Labels: wasmlanche
