Repository ava-labs/hypersdk, pull requests merged in 2024-09, with the labels that each got.

#1485 Swap misnomer stateful and stateless blocks
  README.md
  api/dependencies.go
  api/indexer/tx_indexer.go
  api/ws/client.go
  api/ws/packer.go
  api/ws/server.go
  builder/dependencies.go
  chain/block.go
  chain/builder.go
  chain/dependencies.go
  chain/processor.go
  extension/externalsubscriber/client.go
  extension/externalsubscriber/option.go
  extension/externalsubscriber/server.go
  gossiper/dependencies.go
  tests/integration/integration.go
  vm/option.go
  vm/proposer_monitor.go
  vm/resolutions.go
  vm/storage.go
  vm/syncervm_client.go
  vm/syncervm_server.go
  vm/verify_context.go
  vm/vm.go
  vm/vm_test.go
Labels: vm devx, cleanup

#1494 Flatten MorpheusVM and add defaultvm helper to provide default options
  examples/morpheusvm/cmd/morpheus-cli/cmd/handler.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/resolutions.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/spam.go
  examples/morpheusvm/cmd/morpheusvm/main.go
  examples/morpheusvm/controller/controller.go
  examples/morpheusvm/registry/registry.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/morpheusvm/tests/workload/workload.go
  examples/morpheusvm/vm/client.go
  examples/morpheusvm/vm/option.go
  examples/morpheusvm/vm/server.go
  examples/morpheusvm/vm/vm.go
  vm/defaultvm/vm.go
Labels: cleanup

#1493 Add a VM with Contract support
  .github/workflows/hypersdk-ci.yml
  api/dependencies.go
  cli/prompt/prompt.go
  examples/vmwithcontracts/.golangci.yml
  examples/vmwithcontracts/.goreleaser.yml
  examples/vmwithcontracts/LICENSE
  examples/vmwithcontracts/actions/call.go
  examples/vmwithcontracts/actions/call_test.go
  examples/vmwithcontracts/actions/deploy.go
  examples/vmwithcontracts/actions/publish.go
  examples/vmwithcontracts/actions/transfer.go
  examples/vmwithcontracts/actions/transfer_test.go
  examples/vmwithcontracts/assets/hypersdk.png
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/action.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/chain.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/errors.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/genesis.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/handler.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/key.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/prometheus.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/resolutions.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/root.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/cmd/spam.go
  examples/vmwithcontracts/cmd/vmwithcontracts-cli/main.go
  examples/vmwithcontracts/cmd/vmwithcontracts/main.go
  examples/vmwithcontracts/cmd/vmwithcontracts/version/version.go
  examples/vmwithcontracts/consts/consts.go
  examples/vmwithcontracts/consts/types.go
  examples/vmwithcontracts/go.mod
  examples/vmwithcontracts/go.sum
  examples/vmwithcontracts/scripts/build.release.sh
  examples/vmwithcontracts/scripts/build.sh
  examples/vmwithcontracts/scripts/fix.lint.sh
  examples/vmwithcontracts/scripts/lint.sh
  examples/vmwithcontracts/scripts/run.sh
  examples/vmwithcontracts/scripts/stop.sh
  examples/vmwithcontracts/scripts/tests.integration.sh
  examples/vmwithcontracts/scripts/tests.unit.sh
  examples/vmwithcontracts/storage/errors.go
  examples/vmwithcontracts/storage/programs.go
  examples/vmwithcontracts/storage/recorder.go
  examples/vmwithcontracts/storage/state_manager.go
  examples/vmwithcontracts/storage/storage.go
  examples/vmwithcontracts/tests/e2e/e2e_test.go
  examples/vmwithcontracts/tests/integration/integration_test.go
  examples/vmwithcontracts/tests/workload/workload.go
  examples/vmwithcontracts/vm/client.go
  examples/vmwithcontracts/vm/option.go
  examples/vmwithcontracts/vm/server.go
  examples/vmwithcontracts/vm/vm.go
  scripts/tests.unit.sh
  vm/resolutions.go
Labels: wasmlanche
