Repository ava-labs/hypersdk, pull requests merged in 2024-07, with the labels that each got.

#1043 Return `Result` from public function calls
  x/programs/cmd/simulator/Cargo.toml
  x/programs/cmd/simulator/cmd/plan.go
  x/programs/cmd/simulator/cmd/program.go
  x/programs/cmd/simulator/src/lib.rs
  x/programs/runtime/import_program.go
  x/programs/runtime/import_program_test.go
  x/programs/runtime/import_state.go
  x/programs/runtime/import_state_test.go
  x/programs/runtime/imports.go
  x/programs/runtime/program.go
  x/programs/runtime/serialization.go
  x/programs/runtime/serialization_test.go
  x/programs/runtime/util_test.go
  x/programs/rust/examples/counter-external/src/lib.rs
  x/programs/rust/wasmlanche-sdk/src/program.rs
  x/programs/rust/wasmlanche-sdk/src/state.rs
  x/programs/test/programs/fuel/src/lib.rs
Labels: wasmlanche

#1099 Pass arbitrary type to the simulator
  x/programs/cmd/simulator/cmd/config.go
  x/programs/cmd/simulator/cmd/errors.go
  x/programs/cmd/simulator/cmd/plan.go
  x/programs/cmd/simulator/src/lib.rs
Labels: wasmlanche

#1086 [x/programs] Add balance handling
  x/programs/cmd/simulator/cmd/storage.go
  x/programs/cmd/simulator/cmd/storage_test.go
  x/programs/runtime/call_context.go
  x/programs/runtime/call_context_test.go
  x/programs/runtime/import_balance.go
  x/programs/runtime/import_balance_test.go
  x/programs/runtime/import_program.go
  x/programs/runtime/program.go
  x/programs/runtime/runtime.go
  x/programs/runtime/runtime_test.go
  x/programs/runtime/serialization.go
  x/programs/runtime/util_test.go
  x/programs/rust/examples/counter-external/src/lib.rs
  x/programs/rust/examples/counter/src/lib.rs
  x/programs/rust/sdk-macros/src/lib.rs
  x/programs/rust/wasmlanche-sdk/src/balance.rs
  x/programs/rust/wasmlanche-sdk/src/lib.rs
  x/programs/rust/wasmlanche-sdk/src/program.rs
  x/programs/test/programs/balance/Cargo.toml
  x/programs/test/programs/balance/src/lib.rs
  x/programs/test/programs/call_program/src/lib.rs
  x/programs/test/programs/fuel/src/lib.rs
  x/programs/test/util.go
Labels: wasmlanche

#1137 [ci] Add actionlint job
  .github/actionlint.yml
  .github/workflows/hypersdk-ci.yml
  scripts/tests.actionlint.sh
Labels: ci

#1111 Refactor config interface into value struct
  config/config.go
  examples/morpheusvm/config/config.go
  examples/morpheusvm/controller/controller.go
  examples/tokenvm/config/config.go
  examples/tokenvm/controller/controller.go
  vm/dependencies.go
  vm/network_state_sync.go
  vm/resolutions.go
  vm/storage.go
  vm/syncervm_client.go
  vm/vm.go
  vm/vm_test.go
Labels: refactor

#1139 Implement action test suite helper
  chaintest/action_test_helpers.go
  examples/morpheusvm/actions/transfer_test.go
Labels: testing

#1168 Write some tests for Permissions.Has
  state/keys.go
  state/keys_test.go
Labels: testing

#1196 [ci] Sync lint config from avalanchego
  .github/workflows/hypersdk-ci.yml
  .golangci.yml
  CONTRIBUTING.md
  auth/consts.go
  chain/block.go
  codec/packer_test.go
  codec/type_parser.go
  codec/type_parser_test.go
  crypto/bls/signature.go
  examples/morpheusvm/factory.go
  examples/morpheusvm/scripts/lint.sh
  examples/morpheusvm/tests/integration/integration_test.go
  fetcher/fetcher_test.go
  list/list.go
  scripts/lint.sh
  tstate/tstate_test.go
  utils/utils_test.go
  vm/errors.go
  workers/parallel_workers.go
  workers/parallel_workers_test.go
  x/programs/runtime/import_program.go
  x/programs/runtime/serialization_test.go
  x/programs/test/testdb.go
Labels: ci
