Repository ava-labs/hypersdk, pull requests merged in 2024-10, with the labels that each got.

#1613 Replace usage of `internal/network` with `p2p`
  examples/morpheusvm/go.mod
  examples/morpheusvm/go.sum
  examples/morpheusvm/scripts/run.sh
  examples/vmwithcontracts/go.mod
  examples/vmwithcontracts/go.sum
  examples/vmwithcontracts/scripts/run.sh
  go.mod
  go.sum
  internal/gossiper/gossiper.go
  internal/gossiper/manual.go
  internal/gossiper/proposer.go
  internal/network/network.go
  vm/network_state_sync.go
  vm/network_tx_gossip.go
  vm/syncervm_client.go
  vm/vm.go
Labels: cleanup

#1622 Add JSON marshalling for fee dimensions
  fees/dimension.go
  fees/dimension_test.go
Labels: apis

#1623 Reduce tests.unit.sh timeout value less than CI job
  scripts/tests.unit.sh
Labels: testing

#1625 Re-mark pubsub tests as flaky
  pubsub/server_test.go
Labels: testing

#1627 Add JSON marshalling to Result
  chain/result.go
  chain/result_test.go
  codec/hex.go
Labels: apis

#1638 DSMR storage
  dsmr/README.md
  dsmr/chunk.go
  dsmr/storage.go
  dsmr/storage_test.go
  internal/mempool/mempool.go
  vm/vm.go
Labels: dsmr

#1639 Update DSMR README
  dsmr/README.md
  dsmr/storage.go
Labels: dsmr

#1646 Update chunk block executor
  dsmr/README.md
Labels: dsmr

#1652 Fix incorrect naming of stateless block
  chain/block.go
  vm/vm.go
Labels: cleanup
