Repository ava-labs/hypersdk, pull requests merged in 2024-08, with the labels that each got.

#1205 Simulator Interactions via FFI
  .github/actions/install-rust/action.yml
  .gitignore
  Cargo.toml
  go.mod
  go.sum
  x/programs/cmd/simulator/Cargo.toml
  x/programs/cmd/simulator/README.md
  x/programs/cmd/simulator/build.rs
  x/programs/cmd/simulator/cmd/config.go
  x/programs/cmd/simulator/cmd/custom_imports/README.md
  x/programs/cmd/simulator/cmd/errors.go
  x/programs/cmd/simulator/cmd/interpreter.go
  x/programs/cmd/simulator/cmd/key.go
  x/programs/cmd/simulator/cmd/logger.go
  x/programs/cmd/simulator/cmd/plan.go
  x/programs/cmd/simulator/cmd/program.go
  x/programs/cmd/simulator/cmd/root.go
  x/programs/cmd/simulator/cmd/storage.go
  x/programs/cmd/simulator/cmd/storage_test.go
  x/programs/cmd/simulator/simulator.go
  x/programs/cmd/simulator/src/id.rs
  x/programs/cmd/simulator/src/lib.rs
  x/programs/cmd/simulator/test/context_injection/build.rs
  x/programs/cmd/simulator/test/context_injection/src/lib.rs
  x/programs/runtime/runtime_test.go
  x/programs/rust/examples/automated-market-maker/Cargo.toml
  x/programs/rust/examples/counter-external/src/lib.rs
  x/programs/rust/examples/counter/Cargo.toml
  x/programs/rust/examples/counter/src/lib.rs
  x/programs/rust/examples/token/src/lib.rs
  x/programs/rust/wasmlanche-sdk/src/types.rs
  x/programs/simulator/Cargo.toml
  x/programs/simulator/build.rs
  x/programs/simulator/common/callbacks.h
  x/programs/simulator/common/types.h
  x/programs/simulator/ffi/ffi.go
  x/programs/simulator/src/lib.rs
  x/programs/simulator/src/simulator.rs
  x/programs/simulator/src/state.rs
  x/programs/simulator/state/manager.go
  x/programs/simulator/state/state.go
Labels: wasmlanche

#1306 Return runtime error
  x/programs/rust/wasmlanche-sdk/src/types.rs
  x/programs/simulator/ffi/ffi.go
Labels: wasmlanche

#1309 Upload tmpnet network dir after morpheusvm e2e tests
  .github/workflows/hypersdk-ci.yml
Labels: ci, testing, vm devx

#1303 Make integration tests shareable across VMs
  examples/morpheusvm/rpc/jsonrpc_client.go
  examples/morpheusvm/tests/e2e/e2e_test.go
  examples/morpheusvm/tests/integration/integration_test.go
  examples/morpheusvm/tests/workload/workload.go
  tests/integration/integration.go
  tests/workload/transactions.go
Labels: testing, vm devx

#1323 Remove unused server package
  go.mod
  server/allowed_hosts.go
  server/handler.go
  server/router.go
  server/server.go
  server/wrapper.go
Labels: cleanup

#1418 Add height/timestamp getters and setters to simulator
  x/programs/simulator/common/types.h
  x/programs/simulator/src/simulator.rs
Labels: wasmlanche

#1332 Remove unused utils
  cli/utils.go
Labels: cleanup

#1423 Required Runtime Changes to enable a VM that uses the wasmlanche runtime
  x/programs/runtime/call_context_test.go
  x/programs/runtime/import_balance_test.go
  x/programs/runtime/import_program.go
  x/programs/runtime/import_program_test.go
  x/programs/runtime/program.go
  x/programs/runtime/runtime.go
  x/programs/runtime/runtime_test.go
  x/programs/runtime/util_test.go
  x/programs/rust/examples/automated-market-maker/src/lib.rs
  x/programs/rust/sdk-macros/src/lib.rs
  x/programs/rust/wasmlanche-sdk/src/context.rs
  x/programs/rust/wasmlanche-sdk/src/lib.rs
  x/programs/rust/wasmlanche-sdk/src/state.rs
  x/programs/rust/wasmlanche-sdk/src/types.rs
  x/programs/simulator/build.rs
  x/programs/simulator/common/types.h
  x/programs/simulator/ffi/ffi.go
  x/programs/simulator/src/bindings.rs
  x/programs/simulator/src/simulator.rs
  x/programs/simulator/src/state.rs
  x/programs/simulator/state/manager.go
  x/programs/simulator/state/state.go
  x/programs/test/programs/deploy_program/src/lib.rs
  x/programs/test/util.go
Labels: wasmlanche

#1442 Remove cli lambda funcs
  cli/chain.go
  cli/cli.go
  cli/dependencies.go
  cli/key.go
  cli/prometheus.go
  cli/prompt/prompt.go
  cli/spam.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/action.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/chain.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/handler.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/key.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/prometheus.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/resolutions.go
  examples/morpheusvm/cmd/morpheus-cli/cmd/root.go
  examples/morpheusvm/go.mod
  examples/morpheusvm/go.sum
  fees/manager.go
  go.mod
  go.sum
  prometheus/prometheus.go
Labels: vm devx, cleanup

#1486 Reduce e2e test runtime by reducing tx check interval and reducing StateSyncMinBlocks for e2e setup
  api/indexer/client.go
  api/jsonrpc/client.go
  examples/morpheusvm/controller/client.go
  examples/morpheusvm/tests/workload/workload.go
  tests/e2e/e2e.go
  tests/fixture/subnet.go
  tests/workload/transactions.go
Labels: ci, testing, cleanup
