Repository ava-labs/hypersdk, pull requests merged in 2025-04, with the labels that each got.

#2007 Update docs for prerequisites and golang version maintenance
  CONTRIBUTING.md
  go.mod
Labels: documentation

#2015 Ensure the avalanchego binary is always current with a version-checked install
  .envrc
  bin/avalanchego
  bin/tmpnetctl
  examples/morpheusvm/scripts/run.sh
  scripts/install_versioned_binary.sh
  scripts/run_avalanchego.sh
  scripts/run_tmpnetctl.sh
Labels: testing

#2029 [e2e] Add Dedicated Load Factory
  examples/morpheusvm/tests/e2e/e2e_test.go
  examples/morpheusvm/tests/workload/genesis.go
  tests/e2e/e2e.go
Labels: ci, testing

#2031 [context] Enforce Documentation Standard
  .golangci.yml
  context/config.go
  context/doc.go
Labels: documentation
